Controllers/CreateNoteController.cs
using Microsoft.AspNetCore.Mvc;
using NoteTakerWebApp.Models;

namespace NoteTakerWebApp.Controllers
{
    public class CreateNoteController : Controller
    {
        private readonly ApplicationDbContext _db;

        //This constructor allows us to access the DB in this controller class and everywhere else in the code since public
        public CreateNoteController(ApplicationDbContext db)
        {
            _db = db;
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}

        public IActionResult Index()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateNewNote(Notes note)
        {
            if (ModelState.IsValid)
            {
                note.UserId = UserStatic.UserID;
                _db.Notes.Add(note);
                _db.SaveChanges();
                TempData["sucess"] = "Note was created successfully!";
                return RedirectToAction("Index", "ViewNotes");
            }

            else
            {
                TempData["Fail"] = "Note was note created please try again!";
                return View("Index");
            }
   
        }
        
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NoteTakerWebApp.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace NoteTakerWebApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly ApplicationDbContext _db;

        //This constructor allows us to access the DB in this controller class and everywhere else in the code since public
        public LoginController(ApplicationDbContext db)
        {
            _db = db;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        //public IActionResult Login()
        //{
        //    return View();
        //}

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(User user)
        {
            if (ModelState.IsValid)
            {
                List<User> userList = _db.Users.ToList();

                //User user = new User();
                if (userList.Count() != 0)
                {
                    User loginUser = new User();
                    loginUser = userList.Where(a => a.Username.Equals(user.Username) && a.Password.Equals(user.Password)).FirstOrDefault();
                    if (loginUser != null)
                    {
                        UserStatic.UserName = loginUser.Username.ToString();
                        UserStatic.UserID = loginUser.Id;
                        TempData["UserID"] = loginUser.Id.ToString();
                        TempData["UserName"] = loginUser.Username.ToString();
                        return RedirectToAction("Index", "ViewNotes");
                    }

                    //MessageBox.Show("No values in db  with that username or password");
                    else
                    {
                        TempData["Fail"] = "No users found in the db";
                        return RedirectToAction("Index");
                        //return NotFound();
                    }

                }

            }

            return View("Index");
        }

        public IActionResult UserDashBoard(int Id)
        {
            List<User> userList = _db.Users.ToList();
            User loginUser = new User();
            loginUser = userList.Where(a => a.Id.ToString() == (UserStatic.UserID.ToString())).FirstOrDefault();
            return View(loginUser);
        }

        public IActionResult EditUser(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var user = _db.Users.Find(id);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditUser(User user)
        {
            return View();
        }

        public IActionResult Logout() 
        {
            UserStatic.UserName = "";
            UserStatic.UserID = 0;
            return RedirectToAction("Index", "Home"); 
        }    
    }


}

Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NoteTakerWebApp.Models;

namespace NoteTakerWebApp.Controllers
{
    public class RegisterController : Controller
    {
        private readonly ApplicationDbContext _db;

        //This constructor allows us to access the DB in this controller class and everywhere else in the code since public
        public RegisterController(ApplicationDbContext db)
        {
            _db = db;
        }

        //Lists all users in the DB
        public IActionResult Index()
        {
            //var objUserList = _db.Users.ToList();
            IEnumerable<User> users = _db.Users.ToList();
            return View(users);
        }

        //GET
        public IActionResult CreateUser()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateUser(User user)
        {
            //Use ModelState.AddModelError to add error on the html side of things
            if(ModelState.IsValid)
            {
                _db.Users.Add(user);
                _db.SaveChanges();
                TempData["sucess"] = user.Username + " was created successfully!";
                UserStatic.UserName = user.Username.ToString();
                UserStatic.UserID = user.Id;
                return RedirectToAction("Index", "ViewNotes");
                //return RedirectToAction("Index");
                //return RedirectToAction("Index", "Home");
            }

            return View(user); 
        }
    }
}

Views/Shared/View.cshtml
@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_LoginLayout.cshtml/";
}

<h1>View</h1>

Views/Shared/_EditModalPartial.cshtml
@model IEnumerable<NoteTakerWebApp.Models.Notes>

@if (ViewData["editNote"] != null)
{
    Console.WriteLine(ViewData["editNote"]);
}

<div class="modal fade" id="editNoteData" role="dialog">
    <div class="modal-dialog err-pop" style="">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Edit Current Note</h2>
                <a id="DivClose" class="btn-close" data-dismiss="modal" asp-controller="ViewNotes" asp-action="Index"></a>
            </div>
            <div class="modal-body" style="text-align:center;">
                <form id="editForm">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="" id="editId" value="editId" />
                        <div class="form-group">
                        <label asp-for=@ViewData["editNote"] value=@ViewData["editNote"] class="control-label"></label>
                        <input asp-for="@ViewData["editNote"]" value="@ViewData["editNote"]" class=" form-control" />
                        <span asp-validation-for="@NotesStatic.Title" class="text-danger"></span>
                        </div>
                   
                    
                    @*<div class="form-group">
                    <label asp-for="@item.Description" class="control-label"></label>
                    <textarea asp-for="@item.Description" class="form-control" cols="6" rows="6"></textarea>
                    <span asp-validation-for="@item.Description" class="text-danger"></span>
                    </div>*@
                    @*                   <div class="form-group">
                    <label asp-for="@Model.FirstOrDefault().UserId" class="control-label"></label>
                    <input asp-for="@Model.FirstOrDefault().UserId" class="form-control" />
                    <span asp-validation-for="@Model.FirstOrDefault().UserId" class="text-danger"></span>
                    </div>*@
                </form>
            </div>
            <div class="modal-footer">
                <div>
                    <a id="updateNote" type="submit" value="Update" class="btn btn-primary" />
                    <a class="btn btn-primary" asp-controller="ViewNotes" asp-action="Index">Cancel</a>
                    @*                    <a class="btn btn-primary" id="deleteData" asp-controller="ViewNotes">Delete</a>*@
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NoteTakerWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NoteTakerWebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Index">NoteTakerWebApp <i class="bi bi-pencil-fill"></i></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="CreateUser">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NoteTakerWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NoteTakerWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NoteTakerWebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">

    
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="UserDashboard">NoteTakerWebApp <i class="bi bi-pencil-fill"></i></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CreateNote" asp-action="">Create Notes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ViewNotes" asp-action="">View Notes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NoteTakerWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NoteTakerWebApp</title>
    <link rel="stylesheet" href="./../lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="./../css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="./../NoteTakerWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="UserDashboard">NoteTakerWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CreateNote" asp-action="CreateNewNote">Create Notes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ViewNotes" asp-action="ViewNotes">View Notes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Logout" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NoteTakerWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="./../lib/jquery/dist/jquery.min.js"></script>
    <script src="./../lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="./../js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>