Controllers/ViewNotesController.cs
using Microsoft.AspNetCore.Mvc;
using NoteTakerWebApp.Models;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace NoteTakerWebApp.Controllers
{
    public class ViewNotesController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ViewNotesController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var notes = _db.Notes.Where(userNotes => userNotes.UserId == UserStatic.UserID).ToList();
            //notes = _db.Notes.Where(userNotes => userNotes.UserId == UserStatic.UserID);
            ViewBag.Notes = notes;
            return View(notes);
        }

        [HttpGet]
        public IActionResult SearchNotes(string searchTerm)
        {
            
            if (searchTerm == null)
            {
                //nothing
                return RedirectToAction("Index");

            }

            var searchquery = _db.Notes.Where(userNotes => userNotes.Name == searchTerm).ToList();
            if(searchquery != null)
            {
                ViewData["Getnotesdetails"] = searchTerm;
                return View("Index", searchquery);
            }

            else
            {
                 return RedirectToAction("Index");
            }
            
        }

        [HttpPost]
        public IActionResult Delete(int?id)
        {
            try
            {
                var note = _db.Notes.FirstOrDefault(x => x.Id == id);
                if (note == null)
                {
                    return NotFound();
                }

                _db.Notes.Remove(note);
                _db.SaveChanges();

                //return PartialView("_DeletePartialView", note);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }

        //POST
        public ActionResult EditNotes(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var note = _db.Notes.Find(id);
            //NotesStatic.Title = note.Name.ToString();
            //NotesStatic.ID = note.Id;
            //NotesStatic.Description = note.Description;

            if (note == null)
            {
                return NotFound();
            }

            //return PartialView("_EditModalPartial");
            return View(note);
        }

        //POST
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult EditNotes(Notes note)
        {
            try
            {
                //Notes updatedNotes = _db.Notes.FirstOrDefault(x => x.Id == id);
                //note.UserId = UserStatic.UserID;    
                if (note == null) { return NotFound(); }

                if (ModelState.IsValid)
                {
                    _db.Notes.Update(note);
                    _db.SaveChanges();
                    //return RedirectToAction("Index");
                    //return NotFound();
                }

                //return PartialView("_EditModalPartial", note);

                return RedirectToAction("Index");

                //return View(note);      

            }
            catch (Exception ex)
            {
                throw ex;
            }

        }
    }
}

Views/ViewNotes/EditNotes.cshtml
@model NoteTakerWebApp.Models.Notes

@{
    ViewData["Title"] = "EditNotes";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h1>Edit Notes</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-controller="ViewNotes" asp-action="EditNotes">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ViewNotes/Index.cshtml
@model IEnumerable<NoteTakerWebApp.Models.Notes>
@*@model NoteTakerWebApp.Models.Notes*@

@{
    ViewData["Title"] = "ViewNotes";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

@if (TempData["sucess"] != null)
{
    <h2>@TempData["sucess"]</h2>
}


@*<partial name="_EditModalPartial" />*@

<h1>View @UserStatic.UserName.ToString() Notes</h1>
<hr />

<div class="modal fade" id="confirmDelete" role="dialog">
    <div class="modal-dialog err-pop" style="">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Confirm Delete</h2>
                <a id="DivClose" class="btn-close" data-dismiss="modal" asp-controller="ViewNotes" asp-action="Index"></a>
            </div>
            <div class="modal-body" style="text-align:center;">
                Are you sure you want to delete this note?
            </div>
            <div class="modal-footer">
                <div>
                    <a class="btn btn-primary" asp-controller="ViewNotes" asp-action="Index">Cancel</a>
                    <a class="btn btn-primary" id="deleteData" asp-controller="ViewNotes">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>
<form method="get" asp-controller="ViewNotes" asp-action="SearchNotes">
    <p>
        <input type="search" value="@ViewData["Getnotesdetails"]" name="searchTerm" placeholder="Search by title" />
        <input type="submit" value="Search" class="btn btn-primary">
    </p>
</form>
@*<div class="input-group">
    <div class="form-outline">
        <input type="search" id="form1" class="form-control" />
        <label class="form-label" for="form1">Search</label>
    </div>
    <a class="btn btn-primary" asp-controller="ViewNotes" asp-action="SearchNotes" asp-route-id="@item.Id">
        <i class="fas fa-search"></i>
    </a>
</div>*@
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-4">
            <div class="card" style="width:400px;margin:10px; background-color: lightcyan;">
                <div class="card-body">
                    <h5 class="card-title">@item.Name</h5>
                    <p class="card-title">@item.Description</p>
                    <a class="btn btn-primary" asp-controller="ViewNotes" asp-action="EditNotes" asp-route-id="@item.Id">Edit</a>
                    @*<a class="btn btn-primary" id="showMod" onclick="ConfirmEdit(@item.Id)">Edit</a>*@
                    @*@Html.ActionLink("Delete","Delete", new { id=item.Id }, new { @class = "btn btn-primary", id="confirmDelete"+item.Id})*@
                    <a class="btn btn-primary" id="showModal" onclick="Confirm(@item.Id)">Delete</a>
@*                    <a class="btn btn-primary" id="confirmDelete" data-toggle="modal" data-target="confirmDelete">Delete</a>
*@                    @*<button type="button" name="btnLink" id="btnLink" class="btn btn-primary" asp-controller="ViewNotes" asp-action="Delete" asp-route-id="@item.Id">Open Pop</button>*@
                    @*@await Html.PartialAsync("_DeletePartialView", item)*@
                </div>
            </div>
        </div>

    }

</div>


<script src="https://code.jquery.com/jquery-1.10.0.min.js"
        integrity="sha256-2+LznWeWgL7AJ1ciaIG5rFP7GKemzzl+K75tRyTByOE="
        crossorigin="anonymous"></script>


<script>
        
        var Confirm = function (id) {

            $("#deleteId").val(id);
            $("#confirmDelete").modal('show');
        }


        $("#create").click(function () {
            $('#confirmDelete').modal('show');
        })

        //$("#editNote").click(function () {
        //    $('#editNoteData').modal('show');
        //})

        $("#deleteData").click(function ()
        {
            
            var _id = $("#deleteId").val();
            console.log(_id);
                $.ajax({
                    type:"POST",
                    url: '/ViewNotes/Delete',
                    data: { id: _id },
                    success: function(data){
                        $("#confirmDelete").modal('hide');
                        setInterval('location.reload()', 7000);
                        //$("#wrapper").Html(data);
                        //$("body").html(result);
                        ////$("#confirmDelete").modal('hide');
                        //$("#deleteId").val(null);
                        //setInterval('location.reload()', 7000);
            }
                   
                })

        })  
    
</script>

 @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ViewNotes/_DeletePartialView.cshtml
@model NoteTakerWebApp.Models.Notes

<div class="modal fade" id="confirmDelete1" role="dialog">
    <div class="modal-dialog err-pop" style="">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Confirm Delete</h2>
                <a id="DivClose" class="btn-close" data-dismiss="modal" asp-controller="ViewNotes" asp-action="Index"></a>
            </div>
            <div class="modal-body" style="text-align:center;">
                Are you sure you want to delete this note?
            </div>
            <div class="modal-footer">
                <div>
                    <a class="btn btn-primary" data-toggle="modal" data-target="confirmDelete" asp-controller="ViewNotes" asp-action="Index">Cancel</a>
                    <a class="btn btn-primary" data-toggle="modal" data-target="confirmDelete" asp-controller="ViewNotes" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    $("#confirmDelete+@Model.Id").click(function () {
        $('#confirmDelete1').modal('show');
    })
</script>